### ISSUE TITLE
Debug Barter on iOS

### ISSUE THREAD

**Issue by ptrgags** [ptrgags/barter#50]
I tried to show a friend the website for Barter yesterday. I was getting no story data displayed. I'm guessing it's a problem with ES 6 features that are not supported, but I need to learn how to debug iOS devices on Windows.

**Comment by ghost** [comment]
**Remotely Debugging Mobile Web Pages**
1. Clone _jsconsole_ (https://github.com/remy/jsconsole)
2. Host _jsconsole_ (Node or otherwise)
3. Visited the hosted _jsconsole_ and enter `:listen`
4. Copy the`<script>...</script>` tag into your web application.
5. Host your web application.
6. Visit the web application on the remote device, e.g., iPhone.
7. Console information should show up on the hosted _jsconsole_ page.

In the case of _Barter_, it seems Safari builds shipped up to and including iOS 9 do not support arrow functions. Replacing them with anonymous functions fixed the web page for my iOS 9.3.5 device.

You can find a table of supported ES6 functions for iOS 9 (and other devices) here:
https://kangax.github.io/compat-table/es6/ 

iOS 10 and above should fully support the standard (https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html#//apple_ref/doc/uid/TP40014305-CH11-DontLinkElementID_6)

**Comment by ptrgags** [comment]
Thanks so much for investing the issue!

I used babel to transpile my code from ES6 -> ES5, the next release should work on iOS
